DROP DATABASE IF EXISTS NEWSPAPER_DELIVERY_SYSTEM;
CREATE DATABASE NEWSPAPER_DELIVERY_SYSTEM;
USE NEWSPAPER_DELIVERY_SYSTEM;

DROP TABLE IF EXISTS DELIVERY_DOCKETS;
CREATE TABLE IF NOT EXISTS DELIVERY_DOCKETS (
	deliveryDocketID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    publicationID INTEGER NOT NULL,
    deliveryAreaID INTEGER NOT NULL,
    customerID INTEGER NOT NULL
);

INSERT INTO DELIVERY_DOCKETS VALUES (DEFAULT, 1, 1, 1);

SELECT 
    *
FROM
    DELIVERY_DOCKETS;